# Generated by Django 4.2 on 2024-07-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
