# Generated by Django 4.2 on 2024-07-17 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def set_default_user(apps, schema_editor):
    WorkExperience = apps.get_model('resume', 'WorkExperience')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    default_user = User.objects.first()  # or any logic to get the default user
    for work_experience in WorkExperience.objects.all():
        work_experience.user = default_user
        work_experience.save()

class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_remove_workexperience_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='achievements',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='responsibilities',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='skills_used',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_default_user),
        migrations.AlterField(
            model_name='workexperience',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]